/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_romainpiel_darktown_MarkDownParser */

#ifndef _Included_com_romainpiel_darktown_MarkDownParser
#define _Included_com_romainpiel_darktown_MarkDownParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_romainpiel_darktown_MarkDownParser
 * Method:    markdownToHtml
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_romainpiel_darktown_MarkDownParser_markdownToHtml
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
